In [1]:
import pandas as pd

In [2]:
measurements = pd.read_csv("hawaii_measurements.csv")
station = pd.read_csv("hawaii_stations.csv")

In [4]:
measurements

           station        date  prcp  tobs
0      USC00519397  2010-01-01  0.08    65
1      USC00519397  2010-01-02  0.00    63
2      USC00519397  2010-01-03  0.00    74
3      USC00519397  2010-01-04  0.00    76
4      USC00519397  2010-01-06   NaN    73
5      USC00519397  2010-01-07  0.06    70
6      USC00519397  2010-01-08  0.00    64
7      USC00519397  2010-01-09  0.00    68
8      USC00519397  2010-01-10  0.00    73
9      USC00519397  2010-01-11  0.01    64
10     USC00519397  2010-01-12  0.00    61
11     USC00519397  2010-01-14  0.00    66
12     USC00519397  2010-01-15  0.00    65
13     USC00519397  2010-01-16  0.00    68
14     USC00519397  2010-01-17  0.00    64
15     USC00519397  2010-01-18  0.00    72
16     USC00519397  2010-01-19  0.00    66
17     USC00519397  2010-01-20  0.00    66
18     USC00519397  2010-01-21  0.00    69
19     USC00519397  2010-01-22  0.00    67
20     USC00519397  2010-01-23  0.00    67
21     USC00519397  2010-01-24  0.01    71
22     USC00519397  2010-01-25  0.00    67
23     USC00519397  2010-01-26  0.04    76
24     USC00519397  2010-01-27  0.12    68
25     USC00519397  2010-01-28  0.00    72
26     USC00519397  2010-01-30   NaN    70
27     USC00519397  2010-01-31  0.03    67
28     USC00519397  2010-02-01  0.01    66
29     USC00519397  2010-02-03   NaN    67
...            ...         ...   ...   ...
19520  USC00516128  2017-07-24  0.84    77
19521  USC00516128  2017-07-25  0.30    79
19522  USC00516128  2017-07-26  0.30    73
19523  USC00516128  2017-07-27  0.00    75
19524  USC00516128  2017-07-28  0.40    73
19525  USC00516128  2017-07-29  0.30    77
19526  USC00516128  2017-07-30  0.30    79
19527  USC00516128  2017-07-31  0.00    74
19528  USC00516128  2017-08-01   NaN    72
19529  USC00516128  2017-08-02  0.25    80
19530  USC00516128  2017-08-03  0.06    76
19531  USC00516128  2017-08-05   NaN    77
19532  USC00516128  2017-08-06   NaN    79
19533  USC00516128  2017-08-07  0.05    78
19534  USC00516128  2017-08-08  0.34    74
19535  USC00516128  2017-08-09  0.15    71
19536  USC00516128  2017-08-10  0.07    75
19537  USC00516128  2017-08-11   NaN    72
19538  USC00516128  2017-08-12  0.14    74
19539  USC00516128  2017-08-13   NaN    80
19540  USC00516128  2017-08-14  0.22    79
19541  USC00516128  2017-08-15  0.42    70
19542  USC00516128  2017-08-16  0.42    71
19543  USC00516128  2017-08-17  0.13    72
19544  USC00516128  2017-08-18   NaN    76
19545  USC00516128  2017-08-19  0.09    71
19546  USC00516128  2017-08-20   NaN    78
19547  USC00516128  2017-08-21  0.56    76
19548  USC00516128  2017-08-22  0.50    76
19549  USC00516128  2017-08-23  0.45    76

[19550 rows x 4 columns]

In [ ]:
measurements = measurements.dropna()
station = station.dropna()

In [ ]:
measurements.to_csv("measurementsClean.csv")
station.to_csv("stationClean.csv")